### ISSUE TITLE
Using LOLIN D32 PRO and BME280

### ISSUE THREAD

**Issue by yobl** [nanoframework/Home#1005] opened 2022-03-30 08:24 UTC
### Tool

Visual Studio extension

### Description

Non-functional breakpoints
My approach was requested by José Simões

### How to reproduce

Non-reproducible problem
LOLIN D32 PRO with BME280. I2C protocol.
Visual Studio 2022 version 17.1.2
.NET NanoFramework Extension version 2022.1.0.30
Packages : nanoFramework.CoreLibrary.1.12.0-preview.19, nanoFramework.Hardware.Esp32.1.3.5-preview.10, nanoFramework.Iot.Device.Bmxx80.1.0.288-preview.114 and associated packages
Installation of two breakpoints
![Pb_1](https://user-images.githubusercontent.com/5153209/160784641-8284d131-3442-42be-8b23-533bed6a80af.jpg)
[Pb_1.txt](https://github.com/nanoframework/Home/files/8378488/Pb_1.txt)
[VsProjectFault_59952a57-8ebc-4b77-bf5a-e671bdfc471e.failure.txt](https://github.com/nanoframework/Home/files/8378489/VsProjectFault_59952a57-8ebc-4b77-bf5a-e671bdfc471e.failure.txt)

### Expected behaviour

Stopping at breakpoints

### Aditional context

After making a new attempt, the issue disappeared
![Tst_2](https://user-images.githubusercontent.com/5153209/160785325-3d14b5e6-dd7b-415e-88a9-34ddb1476092.jpg)
[Tst_2.txt](https://github.com/nanoframework/Home/files/8378527/Tst_2.txt)

**Comment by josesimoes** [comment] 2022-04-29 18:04
This is most likely caused by the amount of data that's being requested to the device.
All those fields and properties that you see on the locals and watch have to be fetched from the device each time a breakpoint it hit.
The same applies to the mouse over to show details on popup.

Suggest that you keep that to a minimum and that only add watches to the ones necessary. 

Closing this as we can't solve it.

**Closed by josesimoes** 2022-04-29 18:04 UTC
Labels: Type: Bug, Status: Waiting triage
