### ISSUE TITLE
nanoff do not detect esp32-c3 device after flash and reboot

### ISSUE THREAD

**Issue by goblinmaks** [nanoframework/Home#1445] opened 2024-02-23 17:04 UTC
### Tool

nanoff

### Description

Device detected and flashed but not working with VS extesnion

### How to reproduce

nanoff 2.5.58+849126c120
1. use nanoff to flash firmware
2. nanoff --listdevices

### Expected behaviour

Device displayed in list of available deviices

### Screenshots

![image](https://github.com/nanoframework/Home/assets/1436234/3ec39bb5-6c22-4d2b-b6b9-2bb5dc3b46ab)
![image](https://github.com/nanoframework/Home/assets/1436234/c32743e6-fe99-41d5-b6d3-4d51d7cf0512)

**Comment by alberk8** [comment] 2024-02-24 05:16
It looks like the nF firmware is loaded successfully.   Putty must not be running for VS to detect the ESP32 device.  COM port use  is exclusive.

**Comment by goblinmaks** [comment] 2024-02-24 21:41
Sure, but putty connected to onboard serial. putty = COM10, noanoff  = COM9. 
In any case I see same behavior without Putty.

**Comment by alberk8** [comment] 2024-02-25 00:59
What ESP32 C3 module are using?  This is the first time I am seeing 2 serial port for C2.  If this is the case, unplug the other serial leaving the COM10 (without putty running).  Scan for ESP32 in VS.

**Comment by goblinmaks** [comment] 2024-02-25 10:13
It is ESP-C3

**Comment by maurosampietro** [comment] 2024-03-13 09:32
Hi, having kinda the same problem: Esp32-c3 not showing in the device explorer.
I'm new to nanoframework so any help is appreciated


```
nanoff --platform esp32 --serialport COM2 --update --verbosity diag
.NET nanoFramework Firmware Flasher v2.5.58+849126c120
Copyright (C) 2019 .NET Foundation and nanoFramework project contributors


Using COM2 @ 1500000 baud to connect to ESP32.
Reading details from chip...
Executing esptool with the following parameters:
'--port COM2  --chip auto   --after no_reset_stub flash_id'

OK

Connected to:
ESP32-C3 (ESP32-C3 (revision v0.4))
Features Wi-Fi
Flash size 4MB unknown from ST (manufacturer 0x32 device 0x16406)
PSRAM: undetermined
Crystal 40MHz
MAC DC:DA:0C:DD:92:9C


No target name was provided! Using 'ESP32_C3_REV3' based on the device characteristics.

Trying to find ESP32_C3_REV3 in stable repository...OK
Extracting ESP32_C3_REV3-1.9.0.1105.zip...OK

Updating to 1.9.0.1105

Flashing firmware...
Executing esptool with the following parameters:
'--port COM2  --chip esp32c3   --after no_reset_stub read_flash 0x3C0000 0x40000 "C:\Users\Sam\AppData\Local\Temp\tmp672.tmp"'

Read 262144 bytes at 0x3c0000 in 22.9 seconds (91.7 kbit/s)...

Executing esptool with the following parameters:
'--port COM2 --baud 1500000 --chip esp32c3   --after hard_reset write_flash --flash_size 4MB 0x0 "C:\Users\Sam\.nanoFramework\fw_cache\ESP32_C3_REV3\bootloader.bin" 0x10000 "C:\Users\Sam\.nanoFramework\fw_cache\ESP32_C3_REV3\nanoCLR.bin" 0x8000 "C:\Users\Sam\.nanoFramework\fw_cache\ESP32_C3_REV3\partitions_4mb.bin" 0x3C0000 "C:\Users\Sam\AppData\Local\Temp\tmp672.tmp"'


Uploading stub...                                                                                             
Running stub...                                                                                               
Stub running...                                                                                               
Changing baud rate to 1500000                                                                                 
Changed.                                                                                                      
Configuring flash size...                                                                                     
Flash will be erased from 0x00000000 to 0x00004fff...                                                         
Flash will be erased from 0x00010000 to 0x00117fff...                                                         
Flash will be erased from 0x00008000 to 0x00008fff...                                                         
Flash will be erased from 0x003c0000 to 0x003fffff...                                                         
Compressed 18720 bytes to 11621...                                                                            
Writing at 0x00000000... (100 %)                                                                              
Wrote 18720 bytes (11621 compressed) at 0x00000000 in 0.4 seconds (effective 418.3 kbit/s)...                 
Hash of data verified.                                                                                        
Compressed 1079216 bytes to 655515...                                                                         
Writing at 0x00010000... (2 %)                                                                                
Writing at 0x0001ab75... (4 %)                                                                                
Writing at 0x000275e5... (7 %)                                                                                
Writing at 0x0003076c... (9 %)                                                                                
Writing at 0x0003b3b9... (12 %)                                                                               
Writing at 0x00042408... (14 %)                                                                               
Writing at 0x000480c8... (17 %)                                                                               
Writing at 0x0004dcce... (19 %)                                                                               
Writing at 0x00053a4a... (21 %)                                                                               
Writing at 0x00059854... (24 %)                                                                               
Writing at 0x0005fbfa... (26 %)                                                                               
Writing at 0x00065b4b... (29 %)                                                                               
Writing at 0x0006b7fe... (31 %)                                                                               
Writing at 0x00071bd6... (34 %)                                                                               
Writing at 0x00077448... (36 %)                                                                               
Writing at 0x0007c956... (39 %)                                                                               
Writing at 0x00084330... (41 %)                                                                               
Writing at 0x0008b2f6... (43 %)                                                                               
Writing at 0x00090ce7... (46 %)                                                                               
Writing at 0x00096ade... (48 %)                                                                               
Writing at 0x0009ca33... (51 %)                                                                               
Writing at 0x000a283c... (53 %)                                                                               
Writing at 0x000a8a11... (56 %)                                                                               
Writing at 0x000ae1a8... (58 %)                                                                               
Writing at 0x000b3e60... (60 %)                                                                               
Writing at 0x000b9c3c... (63 %)                                                                               
Writing at 0x000c0167... (65 %)                                                                               
Writing at 0x000c5c44... (68 %)                                                                               
Writing at 0x000cb9f3... (70 %)                                                                               
Writing at 0x000d1ab6... (73 %)                                                                               
Writing at 0x000d7d5b... (75 %)                                                                               
Writing at 0x000de1c1... (78 %)                                                                               
Writing at 0x000e4595... (80 %)                                                                               
Writing at 0x000ea804... (82 %)                                                                               
Writing at 0x000f0647... (85 %)                                                                               
Writing at 0x000f74b4... (87 %)                                                                               
Writing at 0x000fefaa... (90 %)                                                                               
Writing at 0x00105da3... (92 %)                                                                               
Writing at 0x0010b7e2... (95 %)                                                                               
Writing at 0x00111663... (97 %)                                                                               
Writing at 0x00117611... (100 %)                                                                              
Wrote 1079216 bytes (655515 compressed) at 0x00010000 in 14.2 seconds (effective 610.0 kbit/s)...             
Hash of data verified.                                                                                        
Compressed 3072 bytes to 136...                                                                               
Writing at 0x00008000... (100 %)                                                                              
Wrote 3072 bytes (136 compressed) at 0x00008000 in 0.1 seconds (effective 473.9 kbit/s)...                    
Hash of data verified.                                                                                        
Compressed 262144 bytes to 797...                                                                             
Writing at 0x003c0000... (100 %)                                                                              
Wrote 262144 bytes (797 compressed) at 0x003c0000 in 2.1 seconds (effective 982.1 kbit/s)...                  
Hash of data verified.                                                                                        
                                                                                                              
Leaving...                                                                                                    
Hard resetting via RTS pin...                                                                                 
OK                                                                                                            
```

**Comment by Ellerbach** [comment] 2024-03-13 15:12
@maurosampietro you can try to add --masserase in the settings
Also, please attached the second port to the PC, that's how the C3 can be seen, not the port you flash. See the previous discussions.

**Comment by maurosampietro** [comment] 2024-03-13 15:48
Thank you for the quick reply, by the way I don’t understand the meaning of  ‘attach the second port to the PC’. Can you please expand on that to let me understand? On 13 Mar 2024, at 16:13, Laurent Ellerbach ***@***.***> wrote:﻿
@maurosampietro you can try to add --masserase in the settings
Also, please attached the second port to the PC, that's how the C3 can be seen, not the port you flash. See the previous discussions.

**Comment by networkfusion** [comment] 2024-03-14 03:56
Second usb port.

**Comment by maurosampietro** [comment] 2024-03-14 07:17
Hi guys, I only have 1 usb port on the PC and my esp32 only have 1 usb type 3 port. On 14 Mar 2024, at 04:56, Robin Jones ***@***.***> wrote:﻿
Second usb port.

**Comment by maurosampietro** [comment] 2024-03-14 08:28
I’m using a ESP32 C3 Super Mini On 14 Mar 2024, at 09:03, alberk8 ***@***.***> wrote:﻿
What is the ESP32 C3 module or Dev board that you are using?

**Comment by maurosampietro** [comment] 2024-03-14 08:46
I’m ok with that, but where can I set manually that the device is on port COM2 so that I can deploy and run my app? On 14 Mar 2024, at 09:40, alberk8 ***@***.***> wrote:﻿

I’m using a ESP32 C3 Super Mini On 14 Mar 2024, at 09:03, alberk8 @.> wrote:﻿ What is the ESP32 C3 module or Dev board that you are using? —Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: @.>

nanoFramework does not have a version of firmware for ESP32 C3  that supports USB CDC mode (USB to Serial).  So the firmware can be loaded but VS 2022 will not be able to see it.

**Comment by alberk8** [comment] 2024-03-14 09:08
Compile your app in VS.  The output directory will be in "c:/project/appname/bin/Debug/"

using nanoff

`nanoff --target ESP32_C3 --serialport COM2 --deploy --image "c:/project/yourappname/bin/Debug/yourappname.bin"`

**Comment by maurosampietro** [comment] 2024-03-14 11:15
Ok thanks!On 14 Mar 2024, at 10:09, alberk8 ***@***.***> wrote:﻿
Compile your app in VS.  The output directory will be in "c:/project/appname/bin/Debug/"
using nanoff
nanoff --target ESP32_C3 --serialport COM2 --deploy --image "c:/project/yourappname/bin/Debug/yourappname.bin"

**Comment by maurosampietro** [comment] 2024-03-15 07:41
Just to be clear: the problem is not only that the device explorer can’t see my device. (In that case I hoped there was something to enter manually).I can deploy with the command line you sent me apparently but still I can’t debug and VS is virtually useless. Am I right?I need to be sure about this cause if the answer is yes I’ll shift to another Esp32 Thank you allOn 14 Mar 2024, at 12:15, Mauro Sampietro ***@***.***> wrote:﻿Ok thanks!On 14 Mar 2024, at 10:09, alberk8 ***@***.***> wrote:﻿
Compile your app in VS.  The output directory will be in "c:/project/appname/bin/Debug/"
using nanoff
nanoff --target ESP32_C3 --serialport COM2 --deploy --image "c:/project/yourappname/bin/Debug/yourappname.bin"

**Comment by alberk8** [comment] 2024-03-15 08:30
Yes you are 100% correct, when deploying it via CLI you do not have debug capabilities via VS 2022.   Can you try the XIAO_ESP32C3 firmware to see if it works with your board?

**Comment by maurosampietro** [comment] 2024-03-15 09:03
Everything works as expected using the XIAO_ESP32C3 firmware!Good call!On 15 Mar 2024, at 09:30, alberk8 ***@***.***> wrote:﻿
Yes you are 100% correct, when deploying it via CLI you do not have debug capabilities via VS 2022.   Can you try the XIAO_ESP32C3 firmware to see if it works with your board?

**Comment by networkfusion** [comment] 2024-05-09 19:47
If fixed, please close.

**Comment by torbacz** [comment] 2024-05-09 20:05
I've just tested it with ESP32_C3_REV3-1.9.1.93 - works and VS can deploy&debug.

**Closed** 2024-05-09 20:58 UTC
Labels: Status: ANSWERED

**Comment by mcpontorez** [comment] 2025-09-18 12:19
This issue is reproduced on firmware ESP32_C3_REV3-1.14.0.2.zip

Using the XIAO_ESP32C3 target helps.
But my microcontroller is starting to get very hot
