### ISSUE TITLE
Socket class unable to receive UDP datagram.  Error 10050.

### ISSUE THREAD

**Issue by dlkay0** [nanoframework/Home#501] opened 2019-07-10 21:45 UTC
## Details about Problem

**Target:** ESP32

**Firmware image version:** develop Tue Jul 9 15:30:16 2019 +0100
+ minor changes to enable LAN8720 in Esp32_Ethernet_Lan8720.cpp

Worked before? Unknown

## Description
When attempting to receive a UDP datagram, nF throws SocketException.  Same code works in Full Framework on Windows.

## Detailed repro steps so we can see the same problem
1.  Open a Socket in UDP datagram mode
2.  Send a UDP packet to the device's IP address/port
3. Observe socket.Available > 0
4. Call socket.Receive or socket.ReceiveFrom
5. SocketException thrown with ErrorCode 10050

## Serial output
```Running...
Got IP: 10.216.139.136
    #### Exception System.Net.Sockets.SocketException - CLR_E_FAIL (1) ####
    #### Message: 
    #### System.Net.Sockets.NativeSocket::recvfrom [IP: 0000] ####
    #### System.Net.Sockets.Socket::ReceiveFrom [IP: 0033] ####
    #### System.Net.Sockets.Socket::ReceiveFrom [IP: 0011] ####
    #### NFApp2_EthTest.Program::Main [IP: 0055] ####
Exception thrown: 'System.Net.Sockets.SocketException' in System.Net.dll
ErrorCode: 10050
System.Net.Sockets.SocketException: Exception was thrown: System.Net.Sockets.SocketException
```
## Other suggested things
I tried unicast and broadcast UDP packets.  I tried various overloads.

## Expected behaviour
UDP packet data received into buffer.

## Additional context

[nFProgram.cs.txt](https://github.com/nanoframework/Home/files/3379486/nFProgram.cs.txt)
[Sender.cs.txt](https://github.com/nanoframework/Home/files/3379491/Sender.cs.txt)

**Comment by josesimoes** [comment] 2019-07-30 09:59
Can't reproduce this.
Tested with your code above (both sender and receiver).

Output from ESP32-WROVER-KIT + sender console app 

![image](https://user-images.githubusercontent.com/1881520/62120176-fa9f9600-b2b8-11e9-82b5-06655d71b45c.png)


Output from STM32F769I-DISCO + sender console app

![image](https://user-images.githubusercontent.com/1881520/62120196-08edb200-b2b9-11e9-801e-a74ab54057dc.png)

**Comment by josesimoes** [comment] 2019-07-30 10:00
Notice your note above about 

> minor changes to enable LAN8720 in Esp32_Ethernet_Lan8720.cpp


Suspec that the reason for failing could be on those changes...

**Comment by josesimoes** [comment] 2019-08-14 14:01
No further developments or feedback from the author. Closing.

**Closed by josesimoes** 2019-08-14 14:01 UTC
Labels: Status: waiting feedback, Type: Question

**Comment by Shraddha246** [comment] 2021-04-09 11:43
Hello NF,
Nanoframework firmware image with Ethernet support for Olimex ESP32-POE board.
We have tried to update NFinterpreter and flashed it on Olimex ESP32-POE board.
We got IP address but we are getting socket exception while connecting to MQTT service. Is there any plan to create separate firamware for ESP32 with Ethernet support. Please let me know. Thanks.
