### ISSUE TITLE
docker: Error response from daemon: CreateFile .azure

### ISSUE THREAD

**Issue by matsujirushi** [nanoframework/Home#1257] opened 2023-03-28 11:53 UTC
### Tool

Visual Studio Code extension

### Description

It is **devcontainer.json** issue.
I get an error when creating a container using Dev Container in my environment.

```
Start: Starting container
[2023-03-28T11:41:07.336Z] Start: Run: docker run --sig-proxy=false -a STDOUT -a STDERR --mount source=/var/run/docker.sock,target=/var/run/docker.sock,type=bind --mount source=C:\SPB_DataC:\Users\takashi/.azure,target=/home/vscode/.azure,type=bind --mount source=nano-bashhistory,target=/home/vscode/commandhistory,type=volume --mount type=volume,src=nf-interpreter-v1.7.4.0-1aba6adb58522cc1c8d0bb923ce143e2,dst=/workspaces --mount type=volume,src=vscode,dst=/vscode -l vsch.local.repository=https://github.com/nanoframework/nf-interpreter/tree/v1.7.4.0 -l vsch.local.repository.volume=nf-interpreter-v1.7.4.0-1aba6adb58522cc1c8d0bb923ce143e2 -l vsch.local.repository.folder=nf-interpreter -l devcontainer.config_file=/workspaces/nf-interpreter/.devcontainer/devcontainer.json --entrypoint /bin/sh vsc-nf-interpreter-15d9f8579b6dc41f7537e27a99fcbc12 -c echo Container started
[2023-03-28T11:41:07.372Z] docker: Error response from daemon: CreateFile C:\SPB_DataC:\Users\takashi\.azure: The filename, directory name, or volume label syntax is incorrect.
```

If I change `${env:HOME}${env:USERPROFILE}` in devcontainer.json to `${env:USERPROFILE}`, the error will not occur.

### Aditional context

* Windows 11 22H2
* Visual Studio Code 1.76.2
* Dev Containers v0.282.0
* Docker Desktop v4.17.1

**Comment by Ellerbach** [comment] 2023-04-18 07:24
@matsujirushi I cannot reproduce your issue. Same configuration on my side. Logs are all clean, all works as expected.

I guess it depends how you've setup your environement. This file is supposed to be adjusted for those kind of reasons.

I'll close this issue as it's not a problem, it's a matter of adjusting your own environement.

**Closed by Ellerbach** 2023-04-18 07:24 UTC
Labels: Status: ANSWERED
