### ISSUE TITLE
esptool: error: argument --chip/-c: invalid choice: 'esp'

### ISSUE THREAD

**Issue by Scriptman** [nanoframework/Home#997] opened 2022-03-16 20:28 UTC
### Tool

nanoff

### Description

Just installed nanoframework and the nanoff tool in visual studio 2022 but i can not upload the empty nanoframework project to my NodeMCU esp8266 nor my Wemos D1 mini.

I execute the command:
`nanoff --platform esp32 --serialport COM11 --update --baud 115200`

Result:
```
.NET nanoFramework Firmware Flasher v2.0.34+a993b238ea
Copyright (C) 2019 .NET Foundation and nanoFramework project contributors


Using COM11 @ 115200 baud to connect to ESP32.
Reading details from chip...
nanoff : Unhandled exception. nanoFramework.Tools.FirmwareFlasher.WriteEsp32FlashException: 
At line:1 char:1
+ nanoff --platform esp32 --serialport COM11 --update --baud 115200
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Unhandled excep...lashException: :String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
usage: esptool [-h]
               [--chip {auto,esp8266,esp32,esp32s2,esp32s3beta2,esp32s3,esp32c3,esp32c6beta,esp32h2,esp8684}]
               [--port PORT] [--baud BAUD]
               [--before {default_reset,usb_reset,no_reset,no_reset_no_sync}]
               [--after {hard_reset,soft_reset,no_reset,no_reset_stub}]
               [--no-stub] [--trace] [--override-vddsdio [{1.8V,1.9V,OFF}]]
               [--connect-attempts CONNECT_ATTEMPTS]
               {load_ram,dump_mem,read_mem,write_mem,write_flash,run,image_info,make_image,elf2image,read_mac,chip_id,flash_id,read_flash_status,write_flash_status,read_flash,verify_flash,erase_flash,erase_region,merge_bin,version,get_security_info}
               ...
esptool: error: argument --chip/-c: invalid choice: 'esp' (choose from 'auto', 'esp8266', 'esp32', 'esp32s2', 'esp32s3beta2', 'esp32s3', 'esp32c3', 'esp32c6beta', 'esp32h2', 'esp8684')

   at nanoFramework.Tools.FirmwareFlasher.EspTool.WriteFlash(Dictionary`2 partsToWrite, Boolean useStandardBaudrate) in D:\a\1\s\nanoFirmwareFlasher\EspTool.cs:line 497
   at nanoFramework.Tools.FirmwareFlasher.EspTool.FindPSRamAvailable() in D:\a\1\s\nanoFirmwareFlasher\EspTool.cs:line 310
   at nanoFramework.Tools.FirmwareFlasher.EspTool.GetDeviceDetails(String targetName, Boolean requireFlashSize) in D:\a\1\s\nanoFirmwareFlasher\EspTool.cs:line 260
   at nanoFramework.Tools.FirmwareFlasher.Program.RunOptionsAndReturnExitCodeAsync(Options o) in D:\a\1\s\nanoFirmwareFlasher\Program.cs:line 411
   at CommandLine.ParserResultExtensions.WithParsedAsync[T](ParserResult`1 result, Func`2 action)
   at nanoFramework.Tools.FirmwareFlasher.Extensions.CommandLineExtensions.WithNotParsedAsync[T](Task`1 task, Func`2 errorFunc) in D:\a\1\s\nanoFirmwareFlasher\Extensions\CommandLineExtensions.cs:line 31
   at nanoFramework.Tools.FirmwareFlasher.Program.Main(String[] args) in D:\a\1\s\nanoFirmwareFlasher\Program.cs:line 85
   at nanoFramework.Tools.FirmwareFlasher.Program.<Main>(String[] args)
```

### Expected behaviour

I expect the firmware to be written to my device.

### Aditional context

Visual Studio 2022 Version 17.1.1
NanoFramework 2022.1.0.26
nanoff 2.0.34+a993b238ea

**Comment by Ellerbach** [comment] 2022-03-17 07:56
> NodeMCU esp8266 nor my Wemos D1 mini

Only ESP8266 are not supported. Only ESP32 and onward are.

So closing this issue as this is not a bug.

**Closed by Ellerbach** 2022-03-17 07:56 UTC
Labels: Type: Bug, Status: Waiting triage
