### ISSUE TITLE
Can't flash STM32F746 Nucleo using nanoff

### ISSUE THREAD

**Issue by dazzalogan** [nanoframework/Home#719] opened 2021-03-12 11:38 UTC
### Details about Problem

**nanoFramework area:** ( Other tools )

**VS version:**

**VS extension version:**

**Target:** STM32F476NUCLEO

**Firmware image version:**

**Device capabilities output:**

### Description

Can't update target using nanoff.

### Detailed repro steps so we can see the same problem

Hi,

I have a Nucleo-F746ZG board but VS2019 Device Explorer is not seeing it connected.
Both USB connections are made to the board.

Package manager console output:

PM> nanoff --target ST_NUCLEO144_F746ZG --update -v diag
nanoFramework Firmware Flasher v1.15.0+96f858f13a
Copyright (C) 2019 nanoFramework project contributors

Trying to find ST_NUCLEO144_F746ZG in developement repository...
Trying to find ST_NUCLEO144_F746ZG in community targets repository...OK
Downloading firmware package...OK
Download location is C:\Users\Darren.Logan\AppData\Local\Temp\b307315b-7dcf-4c55-97e7-79cedd82957a
Updating to 1.6.929.0
Extracting ST_NUCLEO144_F746ZG-1.6.929.0.zip...
Error E1000: No DFU device found. Make sure it's connected and has booted in DFU mode
PM>

Apparently the issue is related to DFU mode, but I'm out of my depth with this - so please help.

Thank you

Regards

**Comment by networkfusion** [comment] 2021-03-13 18:36
As a work around for this (since the board does not seem to be able to handle DFU packages), download the firmware from https://bintray.com/nfbot/nanoframework-images-community-targets/ST_NUCLEO144_F746ZG/1.6.930.0#files and use ST-Link utility to flash the HEX files for nanoBooter and nanoClr

**Comment by networkfusion** [comment] 2021-03-13 18:50
Possible duplicate of #683

**Comment by piwi1263** [comment] 2021-03-13 19:39
@dazzalogan @josesimoes are you using the lates of nanoff since I've got v1.16.0-preview.3+4e0b0c3891. Plus do put your board in DFU mode and try nanoff --listdfu the dfuid should be shown.

**Closed** 2021-03-13 22:58 UTC
Labels: Area: Tools, Priority: High, Type: Bug, up-for-grabs
