### ISSUE TITLE
VS2022: Device Explorer tool window icons missing after VS extension update

### ISSUE THREAD

**Issue by networkfusion** [nanoframework/Home#1009] opened 2022-04-06 22:46 UTC
### Tool

Visual Studio extension

### Description

Currently the icons sometimes "disappear" when the VS2022 nanoFw extension is updated.
This is a potential solution is outlined in "https://stackoverflow.com/questions/58311920/visual-studio-vsix-extension-not-showing-in-tools-menu" (although there are possibily other fixes).
A solution like this "should" be tried before escalation to the VS team, as although there is a workaround (via: devenv /updateConfiguration) it is annoying.

### Screenshots

![image](https://user-images.githubusercontent.com/11439699/162084600-97197535-cbca-4c77-a25d-84f52e43138e.png)

### Aditional context

A test fix was applied via https://github.com/nanoframework/nf-Visual-Studio-extension/pull/710 but it was unsuccessful.

# ⚠️ Issue reported to VS team. Please up-vote and add your comment [here](https://developercommunity.visualstudio.com/t/Image-icons-from-image-catalog-not-showi/10791720)

Previous issues already closed without actually fixing the problem:
https://developercommunity.visualstudio.com/t/VSSDKCPSExtensibility:-Image-Loading-i/10525678
https://developercommunity.visualstudio.com/t/Extension-icons-missing-after-update/10242633

### WORKAROUND
Not working anymore. Leaving it here for reference (After closing Visual Studio, run `devenv /updateConfiguration` from VS developer command prompt).

**Comment by PNPTransistor** [comment] 2022-04-16 23:21
Hi,

Not that this helps - but I'm seeing the same thing. All NF buttons in solution explorer are now blank.

**Comment by Ellerbach** [comment] 2022-04-17 14:01
> Hi,
> 
> Not that this helps - but I'm seeing the same thing. All NF buttons in solution explorer are now blank.

This is how you can fix it, run: `devenv /updateConfiguration` from the developer command prompt. Close all the Visual Studio instances before.

**Comment by oloendithas** [comment] 2022-09-21 12:58
Indeed, deployment feature also restored by running `devenv /updateConfiguration`

**Comment by DaveSchmid** [comment] 2022-12-18 19:44
![image](https://user-images.githubusercontent.com/146932/208316178-45e9d00c-2eab-49c2-9e5e-207d12fe241f.png)

**Comment by josesimoes** [comment] 2023-01-02 15:37
## ⚠️ Issue reported to VS team. Please up-vote [here](https://developercommunity.visualstudio.com/t/Extension-icons-missing-after-update/10242633)!

**Comment by josesimoes** [comment] 2023-01-16 09:22
There are reports of this happening, so the fix may not be that good...
cc @DaveSchmid

**Comment by josesimoes** [comment] 2023-01-17 14:55
Instructions on how to gather a log of issues loading images, taken from [here](https://developercommunity.visualstudio.com/t/Extension-icons-missing-after-update/10242633#TPIN-N10245020-N10254729)

>>>>>>>>

To toggle logging, follow the instructions below. That will create a log file called `ImageLibrary.log` in the `%USERPROFILE%` folder. 

1. Enable the logging with
```
vsregedit set local HKLM “ImageLibrary” TraceLevel string Verbose
vsregedit set local HKLM “ImageLibrary” TraceFilename string ImageLibrary.log
```
2. With VS closed, open a VS developer prompt and run `devenv /updateConfiguration` to ensure any caching issues are captured
3. Then launch VS and ensure your icons are missing to capture any runtime issues. 
4. Grab the log file  `ImageLibrary.log` in the `%USERPROFILE%` folder. 
5. Turn off tracing with
```
vsregedit set local HKLM “ImageLibrary” TraceLevel string Off
```
6. Upload your log in this issue and/or directly at the issue in VS Dev Community [here](https://developercommunity.visualstudio.com/t/Extension-icons-missing-after-update/10242633#TPIN-N10245020-N10254729)

**Comment by DaveSchmid** [comment] 2023-01-17 16:07
I tried it. Now the icons are back. :- ) 
But no ImageLibrary.log on the whole computer.

**Comment by josesimoes** [comment] 2023-03-09 09:46
@TerryFogg do not upin this issue. It's critical and it's meant to be highlighted at the top.

**Comment by TerryFogg** [comment] 2023-03-09 09:49
@josesimoes  Sorry, I don't remember doing this? and I wouldn't normally. I will be a bit more careful

**Comment by matsujirushi** [comment] 2023-03-09 11:59
I did this steps, but VS didn't generate ImageLibrary.log file. 😢
https://github.com/nanoframework/Home/issues/1009#issuecomment-1385553170

![image](https://user-images.githubusercontent.com/8079404/224016353-8b4f4dc2-d1c4-4c7d-810f-d26a37390a0b.png)

![image](https://user-images.githubusercontent.com/8079404/224016580-d17716ca-0106-4a61-8349-2025e9bbba26.png)

**Comment by atboxshop** [comment] 2023-03-24 01:14
So is there any update to solve this problem so far guys?

**Comment by SoaSoftNet** [comment] 2023-04-13 12:17
Thank you for your hard work. Please let me know when you repair it. Thank you.

**Comment by josesimoes** [comment] 2023-04-13 12:28
> Thank you for your hard work. 

Thank you for your kind words.

> Please let me know when you repair it. Thank you.

Just subscribe to the issue that's tracking this and you'll be notified.

**Comment by pt2go** [comment] 2023-05-04 16:30
update to vs2022 17.5.5，the icon coming back..............

**Comment by matsujirushi** [comment] 2023-05-04 23:37
@pt2go me too.

**Comment by atboxshop** [comment] 2023-05-05 01:52
After updating to version 17.5.5, the device explorer appear just 1 time :) and it was disappear after restart visual studio 2022. Pls fix it. Thanks guys.

**Comment by pt2go** [comment] 2023-05-06 12:35
> Still missing icons after updating to version 17.5.5, the device explorer's icons appear just 1 time :) right after the updating and its icons were disappear again after restart visual studio 2022. Pls fix it. Thanks guys.

.......right，icon miss

**Comment by renerlemes** [comment] 2023-05-25 19:54
I updated VS to 17.6.2 version and now is working

**Comment by fhtino** [comment] 2023-05-27 06:12
Updated to VS 17.6.2 and is **not** working  :(

![image](https://github.com/nanoframework/Home/assets/637401/305bc379-f1f3-4852-a6f1-c511d6bc1262)

**Comment by pt2go** [comment] 2023-06-07 03:52
> I updated VS to 17.6.2 version and now is working

my vs with 17.6.2 working perfect!

**Comment by atboxshop** [comment] 2023-06-09 03:38
After updated my nanoframework extension for visual studio to the latest version and updated my visual studio to version 17.6.2, the icon re-appear again and it works perfectly. Thanks guys. 👍

**Comment by fhtino** [comment] 2023-06-09 04:30
I confirm now it's working.  VS 17.6.2 and nanoFramework extension 2022.3.0.60 solved the issue.

**Comment by jouda13** [comment] 2023-07-11 19:56
Hi, I’ve had a bad luck with mine. VS 17.6.5 and nanoFramework extension 2022.3.0.60 . The icons are still missing. Anybody else is having the same issue?

**Comment by Ellerbach** [comment] 2023-07-12 08:39
> Hi, I’ve had a bad luck with mine. VS 17.6.5 and nanoFramework extension 2022.3.0.60 . The icons are still missing. Anybody else is having the same issue?

Yes, I did. Closing all Visual Studio, then openeing the VS Dev command prompt and then running: `devenv /updateConfiguration` did fix the issue.

**Comment by atboxshop** [comment] 2023-07-13 08:04
Confirm that after update vs studio 2022 to version 17.6.5, the icon was disappeared again. I also tried to run the devenv cmd for updating the configuration but could not fix the problem. Pls fix it guys. Thanks

**Comment by atboxshop** [comment] 2023-07-15 03:44
To fix the missing icon after updating vs studio 2022 to 17.6.5, I go to start -> all apps -> Visual Studio 2022 -> x64 native tool command prompt or x86 native tools command prompt . And run this command devenv /updateConfiguration to fix the problem like Ellerbach mention in the previous posting. :D

**Comment by manuel76413** [comment] 2023-08-20 14:06
> devenv /updateConfiguration

doesn't take effect, still blank toolbar, empty icon

**Comment by atboxshop** [comment] 2023-08-21 05:16
Run x64 native tool command prompt as administrator

**Comment by josesimoes** [comment] 2023-09-01 12:28
After updating to v17.7.3 a few days ago, I still have the extension with icons. Hopefully this has been fixed upstream...

**Comment by torbacz** [comment] 2023-09-08 20:28
One week later, icons have disappeared :(

**Comment by atboxshop** [comment] 2023-11-14 03:01
Any updates to fix this issue guys 👍 . My suggestion is that this device explorer window must remove and replace that window by a sub-menu somehow. 👍

**Comment by TerryFogg** [comment] 2023-11-14 03:07
It quite frustrating as it "comes and goes". About a month ago I lost my icons.
The command "devenv /updateconfiguration" run at the developer prompt can fix this sometimes.
I don't have icons at the moment, and this did not fix my problem.
I have been waiting for Microsoft to finish off their new Visual Studio Extension development system which is easier to debug and develop ( I hope). Still waiting and when it comes we could use this

**Comment by TerryFogg** [comment] 2023-11-14 04:26
I did wonder if the fact that our icons are .png and not the older .ico has anything to do with the mishandling by Microsoft code.

**Comment by CoryCharlton** [comment] 2023-11-14 04:59
Not sure if it helps at all but it looks like the issue also impacts the project icons (library and application projects but not unit tests):

![image](https://github.com/nanoframework/Home/assets/10094287/10d12685-8e06-4623-8753-d747a91c2cc0)

**Comment by josesimoes** [comment] 2023-11-14 09:45
> Any updates to fix this issue guys 👍 . My suggestion is that this device explorer window must remove and replace that window by a sub-menu somehow. 👍

How's that? There is already an entry under View menu to show/hide Device Explorer.

**Comment by josesimoes** [comment] 2023-11-14 09:48
If you guys go through the related issue in VS Developer Community you'll see that this has to do with the naming of the resources, and the strong naming and other stuff that VS resource manager is doing trying to find the image resources.
Unrelated with image the format. And yes, it affect anything image resource related... 😞

**Comment by atboxshop** [comment] 2023-11-17 06:32
> > Any updates to fix this issue guys 👍 . My suggestion is that this device explorer window must remove and replace that window by a sub-menu somehow. 👍
> 
> How's that? There is already an entry under View menu to show/hide Device Explorer.
Yes, we can hide or show the device explorer. I means if you guys can create an sub menu (without icon or using default icon) for example it will be like this in Visual Studio : View-->Other Windows-->Device Explorer--> Ping Device or Show Setting. And problem will be solved. 👍

**Comment by josesimoes** [comment] 2023-11-27 09:51
Hey @softworkz! Just read your detailed analysis at developer community issue. Nice.
Thanks for taking the time to investigate this and provide a fix.
We'll be on this ASAP! 👍🏻 🥇

**Comment by Ellerbach** [comment] 2023-11-27 16:02
With 2023.3.0.67 all works fine again! Thanks a lot @softworkz for the deep investigation!

**Comment by softworkz** [comment] 2023-11-28 08:58
The favor is mutual since I learn a lot from existing VS project system extensions. 

Let's help other extensions developers not needing to go through all the trouble by upvoting here:  https://developercommunity.visualstudio.com/t/VSSDKCPSExtensibility:-Image-Loading-i/10525678

and here: https://github.com/microsoft/VSProjectSystem/issues/373

**Comment by networkfusion** [comment] 2023-12-20 14:25
Re-opening as unfortunately it is still occuring.

**Comment by atboxshop** [comment] 2023-12-26 23:53
To fix it temporary, go to extension, disable nanoframework and re-enable it. After that restart your visual studio, all icons will appear.

**Comment by networkfusion** [comment] 2023-12-27 13:49
> To fix it temporary, go to extension, disable nanoframework and re-enable it. After that restart your visual studio, all icons will appear.

Nice workaround!

**Comment by kondr1** [comment] 2024-02-28 10:04
Both workaround doesn't work for me.

**Comment by alberk8** [comment] 2024-02-28 10:13
@kondr1,  Can you try to repair your Visual Studio installation?

**Comment by madschristiansen** [comment] 2024-06-06 06:31
This is a massive issue for newcomers to this project. I have now tried for days to get startet but the fact thatI cant use the vs extension, I cant change network setting (Or at least cant find any other way)
Is it better on older VS version like 2019?

I need it for a POC so I should have been done yesterday but have spend all my time installing/removing/diabling/enabling/running dev commands etc etc.

**Comment by josesimoes** [comment] 2024-06-06 08:16
@madschristiansen I'm totally sympathetic with you on how much this is a pain! 
As you can see from the thread above, this is an issue caused by a 3rd party tool (Visual Studio) of which we don't have any control. 
For some reason, the reports on this problem aren't getting enough love from the VS team. If you could go to the developer community website (URLs above) and add your comments there expressing the need to have this fixed, it would be helpful. Considering that issues there are prioritized according to the impact they are causing to developers.

**Comment by softworkz** [comment] 2024-06-06 12:17
I would recommend to create a support incident with MS about this. Refer to the issue on VS community and ask for escalation.

Three ways to create incidents:

- Either you have a VS subsccription with free incidents include
- you or your company has a support contract
- you can buy individual incidents (expensive, though)

If they don't resolve it, the incident won't be counted as used (but you don't get the money back for the incident package in the 3rd case, yet you can use them otherwise)

**Comment by josesimoes** [comment] 2024-06-12 15:14
For what is worth: after update VS to 17.10.1 and install the latest version of our extension I have the icons back. 🤞🏻 😅

**Comment by mikmog** [comment] 2024-06-14 18:08
Also in Version 17.11.0 Preview 2.0 😊

**Comment by josesimoes** [comment] 2024-08-22 11:02
Looks like this has been fixed by VS Team. Let's wait for the fix to become available.
See [comment](https://developercommunity.visualstudio.com/t/VSSDKCPSExtensibility:-Image-Loading-i/10525678#T-N10728516) in the follow-up issue.

**Comment by zorgoz** [comment] 2024-08-25 17:19
Visual Studio Version 17.12.0 Preview 1.0 (Released August 13th): no icons - neither in the View > Other Windows menu.  The fix referred by @josesimoes might not be included yet. Let's wait and see...

**Comment by ajan0636** [comment] 2024-10-31 14:41
still not working

**Comment by josesimoes** [comment] 2024-11-15 18:32
New issue raised in Developer Community: https://developercommunity.visualstudio.com/t/Image-icons-from-image-catalog-not-showi/10791720

**Closed** 2024-11-22 16:44 UTC
Labels: Type: Bug, Status: Blocked, Area: Visual Studio extension

**Comment by atboxshop** [comment] 2024-11-25 02:32
After getting back all of icons. Now, my esp32 was not detected in device explorer tool. It was detected when I use command nandoff list devices. Try to update firmware 
 and repair/reinstall Visual Studio but still could not got my esp32 detecting in device explorer. Any suggestion guys? 
![pic1](https://github.com/user-attachments/assets/350c6a0e-4bb4-45e0-823e-9c28ac7f343b)
![pic2](https://github.com/user-attachments/assets/b0644a8c-d7c1-4288-ac6f-7bf75c5bdead)
